- Resources/public/css/bootstrap.css
- Resources/public/less/utilities.less
Same as in https://github.com/ezsystems/ezdemo/pull/40 (even if because of https://jira.ez.no/browse/EZP-23919 it's not really needed)
> Sync .less and .css files after fixing EZP-23829

- Features/Content/content.feature
- Features/Content/feedback_form.feature
- Features/Content/place.feature
- Features/Content/premium_content.feature
- Features/Context/Content/Context.php
- Features/Context/Demo.php
In order to test possible regressions of the param converter #129  , we needed to have the modified part covered by BDD.
> Basic bdd improvement

- Controller/DemoController.php
- Controller/FeedbackFormController.php
- Controller/PlaceController.php
- Helper/PlaceHelper.php
- Resources/config/services.yml
Link: https://jira.ez.no/browse/EZP-21998
Modification introduced by adding a Param Converter for Location and Content in the kernel: https://github.com/ezsystems/ezpublish-kernel/pull/1128/
Manual tests. And see if BDD works (thanks to #133) ;)
> EZP-21998: Implement @ParamConverter in controllers

- Controller/FolderController.php
- Features/Content/folder.feature
- Features/Context/Demo.php
- Helper/CriteriaHelper.php
- Resources/config/default_settings.yml
- Resources/config/ezdemo.yml
- Resources/views/aside/folder.html.twig
- Resources/views/aside_sub/folder.html.twig
- Resources/views/full/folder.html.twig
- Resources/views/line/folder.html.twig
This PR includes missing PHP code for displaying Twig version of [folder] content. See also #136
> Missing PHP code for [folder] content

- composer.json
Moved dependency update from #136.
> Added BootstrapJS dependency to composer.json

- Controller/FolderController.php
- Helper/MenuHelper.php
- Helper/PlaceHelper.php
- Menu/Builder.php
https://jira.ez.no/browse/EZP-24092
Also see kernel PR:
https://github.com/ezsystems/ezpublish-kernel/pull/1206
> EZP-24092: Optimize queries to not perform count when not needed

- Resources/public/css/bootstrap.css
- Resources/public/less/layouts.less
Link to Jira task: https://jira.ez.no/browse/EZP-24087
> EZP-24087: Image stretched on the home page of the demo bundle

- Resources/views/pagelayout.html.twig
> https://jira.ez.no/browse/EZP-24052
See https://github.com/ezsystems/LegacyBridge/pull/23
> Fix EZP-24052: Preview causes redirect to versionview not being able to continue editing

- Resources/views/page_footer.html.twig
- Resources/views/page_head_script.html.twig
- Resources/views/page_head_style.html.twig
- composer.json
Link to Jira task: https://jira.ez.no/browse/EZP-24150
Work in progress.
Waiting for:
> EZP-24150: Implement privacy cookie law in demo bundle

- Features/Content/place.feature
- Features/Context/Content/Context.php
> Added missing BDD tests for place and place content

- Resources/config/services.yml
> https://jira.ez.no/browse/EZP-24460
> Fix EZP-24460: Fix service factories deprecation warnings

- Controller/DemoController.php
- Controller/FeedbackFormController.php
> https://jira.ez.no/browse/EZP-24457
See https://github.com/ezsystems/ezpublish-kernel/pull/1286
> Fix EZP-24457: Change Request injection to RequestStack

- Resources/config/ezdemo.yml
- Resources/views/full/file.html.twig
- Resources/views/full/video.html.twig
- Resources/views/line/file.html.twig
- Resources/views/line/video.html.twig
Link to Jira task: https://jira.ez.no/browse/EZP-24466
> EZP-24466: Add views for file and video content types

- Resources/public/css/bootstrap.css
- Resources/public/less/navbar.less
After updating DemoBundle to use the latest Bootstrap https://jira.ez.no/browse/EZP-22361 a regression has been introduced https://jira.ez.no/browse/EZP-20108
https://jira.ez.no/browse/EZP-24482
> Fix EZP-24482 - eZ Demo top menu doesn't appear until added a new folder after EZP-22361

- Resources/views/Security/login.html.twig
- Resources/views/page_header_links.html.twig
> https://jira.ez.no/browse/EZP-24476
Ref https://github.com/ezsystems/ezpublish-kernel/pull/1318
> Fix EZP-24476: Refactor CSRF token generation in Security login form

- Features/Content/start_page.feature
to unblock https://github.com/ezsystems/ezplatform/pull/34
review ping @ezsystems/qa-team
> Add sentence to wait for login link

- Controller/DemoController.php
- Controller/FolderController.php
- Helper/MenuHelper.php
Fix deprecated criteria clause.
JIRA issue: https://jira.ez.no/browse/EZP-24730
> Fix deprecated criteria clause

- Resources/views/fields/ezimage_simple.html.twig
Link to Jira task: https://jira.ez.no/browse/EZP-24717
> EZP-24717: Image alt attribute should not be shown when empty

- Resources/installer/sql/demo_data.sql
Link to Jira task: https://jira.ez.no/browse/EZP-24762
> EZP-24762: Remove unused "New Almighty" content object from demo_data.sql

- Resources/installer/config_templates/ezpublish.yml
> EZP-24745: Make SolrBundle ready for release

- Helper/PlaceHelper.php
- Resources/views/parts/place/place_list.html.twig
Small optimization for places to not have to load full content object and throw it away again as code is only interested in main location id.
> Change Places to use findContentInfo api

- Controller/FolderController.php
The response is create but not used.  Also the content is retrieved but not used.
> EZP-24940: Remove unused Repsonse object in DemoBundle FolderController

- behat.yml
> BDD: moved behat.yml config to demobundle
